FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
RUN apk --no-cache add curl
RUN curl -u admin:123 -o achat-1.0.jar "http://192.168.1.170:8081/repository/maven releases/tn/esprit/rh/achat/1.0/achat-1.0.jar" -L
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8089