version: "3.3"

services:

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp 
    volumes:
      - /home/mysql/data:/home/vagrant/mysql:rw
  
  springboot-app:
  
    image: seifderbali/repodock:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: achatdb
    restart: on-failure
    ports:
      - 8089:8089 
    links:
      - mysql-db